version: '3.7'
services:
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "8181:8181"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  mongodb_container:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    restart: always
    ports:
      - 27017:27017
    depends_on:
      - nginx

  api_whois_container:
    build: .
    ports:
      - 8080:8080
    restart: always
    volumes:
      - /var/git_projects/ip_info_api/logs:/api_whois/logs/
    depends_on:
      - mongodb_container
    dns:
      - 77.88.8.8
      - 8.8.8.8


volumes:
  mongodb_data:
  logs: