version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    restart: always
    ports:
      - 27017:27017

  api_whois_container:
    build: .
    ports:
      - 8080:8080
    restart: always
    volumes:
      - C:/logs:/api_whois/logs/
    depends_on:
      - mongodb_container
    dns:
      - 77.88.8.8
      - 8.8.8.8


volumes:
  mongodb_data:
  logs: